### ISSUE TITLE
观摩网站发现的一些问题

### ISSUE THREAD

**Issue by gdludan** [Freen247/Django_blog#3]
首先，你的文章内容，写的不错。

你的settings.py文件得设置DEBUG=False；
![Snipaste_2019-11-14_14-52-26](https://user-images.githubusercontent.com/37908647/68833444-6d107680-06ee-11ea-83fb-c6f73e914fe6.png)

自定义的get_tools标签一些没有在模版注册
![Snipaste_2019-11-14_14-52-26](https://user-images.githubusercontent.com/37908647/68833750-2ec78700-06ef-11ea-8a37-0a94893cb412.png)

貌似还是个半成品。

愿天堂没有代码，哈哈。

**Comment by Freen247** [comment]
哈哈哈哈，你当时上线的时候我还在调试更改，估计是缓存的原因你没有加载出来，三天前我加了添加工具的功能。以后想发展更多的功能在这个网站里面，确实是还没有完全完成。但是i网站主要的功能都已经实现了。

**Comment by Freen247** [comment]
谢谢浏览
